services:
  postgres:
    build: docker/postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - DATA_SOURCE_USER=${POSTGRES_USER}
      - DATA_SOURCE_PASS=${POSTGRES_PASSWORD}
    ports:
      - "9187:9187"

    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

    configs:
      - source: prometheus_exporter_config
        target: /etc/prometheus/prometheus.yml

    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    configs:
      - source: grafana_config
        target: /etc/grafana/provisioning/datasources/datasources.yml

      - source: grafana_dashboard
        target: /etc/grafana/provisioning/dashboards/dashboard.json

      - source: grafana_dashboard_provider
        target: /etc/grafana/provisioning/dashboards/dashboard-provider.yml

    restart: unless-stopped

  load_generator:
    build: docker/load_generator
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DURATION=120
      - CONCURRENCY=10

    depends_on:
      postgres:
        condition: service_healthy


configs:
  prometheus_exporter_config:
    file: ./configs/prometheus.yml

  grafana_config:
    file: ./configs/datasource.yml

  grafana_dashboard:
    file: ./configs/dashboard.json

  grafana_dashboard_provider:
    file: ./configs/dashboard-provider.yml
